### ISSUE TITLE
Depreciated or Active

### ISSUE THREAD

**Issue by dottenbr** [frappe/knowledge_base#3]
@anandpdoshi is this being depreciated and replaced with the Tools->Notes in Frappe/ERPNext or is this a functional App that will stand separately?

**Comment by rmehta** [comment]
Notes is for internal consumption, kb for external.

**Comment by dottenbr** [comment]
But notes has the ability to make them "public" so I don't see the difference. 

Sent from my mobile

**Comment by rmehta** [comment]
Public within logged in users (on desk)

**Comment by dottenbr** [comment]
​Does that mean that if a note is not public it is only visible to the user
themselves?​

**Comment by rmehta** [comment]
Yeah, its more for private, internal consumption.
